apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-1
  namespace: kafka
  labels:
    app: kafka-broker-1
spec:
  replicas: 1
  selector: { matchLabels: { app: kafka-broker-1 } }
  template:
    metadata: { labels: { app: kafka-broker-1 } }
    spec:
      hostname: kafka-broker-1
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
            - containerPort: 29092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value:  "PLAINTEXT://kafka-broker-1:29092,PLAINTEXT_HOST://kafka-broker-1:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1
  namespace: kafka
spec:
  selector: { app: kafka-broker-1}
  ports:
    - name: external
      port: 9092
      targetPort: 29092
    - name: internal
      port: 29092
      targetPort: 29092
  type: ClusterIP