apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: sap-assignment
  labels:
    app:
      kafka-ui
spec:
  replicas: 1
  selector: { matchLabels: { app: kafka-ui } }
  template:
    metadata: {
      labels: { app: kafka-ui } }
    spec:
      initContainers:
        - name: wait-for-kafka
          image: curlimages/curl:latest
          command: [ 'sh', '-c', 'until nc -z kafka-broker-1 29092; do echo waiting for kafka; sleep 2; done;' ]
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports: [{ containerPort: 8080 }]
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "local"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value:  "kafka-broker-1:29092"



---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: sap-assignment
spec:
  selector: { app: kafka-ui }
  ports:
    - port: 8082
      targetPort: 8080
  type: LoadBalancer
