apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: sap-assignment
spec:
  replicas: 1
  selector:
    matchLabels: { app: api-gateway }
  template:
    metadata:
      labels: { app: api-gateway }
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef: { name: app-config }
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 60
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: sap-assignment
spec:
  selector: { app: api-gateway }
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080    # mappa su porta 30080 del nodo
  type: NodePort
