apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sap-assignment
data:
  # Eureka configuration
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-service:8761/eureka/"
  EUREKA_INSTANCE_HOSTNAME: "eureka-server"
  EUREKA_INSTANCE_PORT: "8761"
  EUREKA_HOST: "eureka-service"

  # API Gateway configuration
  API_GATEWAY_EUREKA_INSTANCE_PORT: "8080"
  API_GATEWAY_EUREKA_INSTANCE_HOSTNAME: "api-gateway"

  # Prometheus configuration
  PROMETHEUS_INSTANCE_PORT: "9090"
  PROMETHEUS_INSTANCE_HOSTNAME: "prometheus"

  # MongoDB configuration
  MONGODB_INSTANCE_HOSTNAME: "mongodb-service"
  MONGODB_INSTANCE_PORT: "27017"
  MONGO_CONNECTION: "mongodb://mongodb-service:27017"

  # User microservice configuration
  USER_INSTANCE_HOSTNAME: "user-microservice"
  USER_INSTANCE_PORT: "8080"
  USER_ADAPTER_RIDE_PORT: "8081"

  # E-bike microservice configuration
  EBIKE_INSTANCE_HOSTNAME: "ebike-microservice"
  EBIKE_INSTANCE_PORT: "8080"
  EBIKE_ADAPTER_RIDE_PORT: "8081"

  # Map microservice configuration
  MAP_INSTANCE_HOSTNAME: "map-microservice"
  MAP_INSTANCE_PORT: "8080"
  MAP_ADAPTER_RIDE_PORT: "8081"
  MAP_ADAPTER_EBIKE_PORT: "8082"

  # Ride microservice configuration
  RIDE_INSTANCE_HOSTNAME: "ride-microservice"
  RIDE_INSTANCE_PORT: "8080"

  # Zookeeper
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"

  # Kafka
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-service:2181"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker-1:29092,PLAINTEXT_HOST://kafka-broker-1:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-broker-1:29092"
  # Kafka UI
  KAFKA_UI_CLUSTER_NAME: "local"
  KAFKA_UI_BOOTSTRAP_SERVERS: "kafka-broker-1:29092"
  KAFKA_UI_SCHEMAREGISTRY_URL: "http://schema-registry:8081"