apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: sap-assignment

spec:
  replicas: 1
  selector:
    matchLabels: { app: eureka-server }
  template:
    metadata:
      labels: { app: eureka-server }
    spec:
      containers:
        - name: eureka-server
          image: eureka-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          envFrom:
            - configMapRef: { name: app-config }
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8761 }
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8761 }
            initialDelaySeconds: 60
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: sap-assignment

spec:
  selector: { app: eureka-server }
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
  type: ClusterIP
