apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: sap-assignment

spec:
  replicas: 1
  selector: { matchLabels: { app: prometheus } }
  template:
    metadata: { labels: { app: prometheus } }
    spec:
      initContainers:
        - name: wait-for-api-gateway
          image: curlimages/curl:latest
          command: [ 'sh', '-c', 'until curl -s http://api-gateway-service:8080/actuator/health | grep -q "UP"; do echo waiting for api-gateway; sleep 2; done;' ]
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports: [{ containerPort: 9090 }]

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: sap-assignment

spec:
  selector: { app: prometheus }
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      nodePort: 30100
  type: NodePort
